### ISSUE TITLE
Setup development environment

### ISSUE THREAD

**Issue by ckruczek** [ckruczek/texpack#2]
We need a runnable development environment. This includes a makefile which handles all files that need to be build, automatic.

**Comment by ckruczek** [comment]
Added makefile and an initial main.c so that make can run without errors.

**Comment by ChrisKujawa** [comment]
gcc or clang?

**Comment by ckruczek** [comment]
Both. I prefer clang but I also want to support gcc. So we need to build against both environments. Also we need a check on the goal system which one is installed.
